name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 'latest'
        - name: Install packages
          run: npm install
        - name: Set Creds
          run: git config user.name "Club Baby Pro" && git config user.email "club.babypro@gmail.com"
        - name: Deploy
          run: npm run deploy
